import CH19_1_MAIN_USE
result=CH19_1_MAIN_USE.add(34,44)
print(result)
print(__name__)

'''NOTE---> IF WE HAVE A print(__name__) IN THE MAIN FILE AND WE ARE RUNNING THE PROGRAMME THERE ITSELF THEN WHAT HEPPENS IS IT OUTPUT AS __MAIN__
             BUT WHEN WE HAVE IMPORTED THAT FILE INTO ANOTHER FILE IN THAT CASE IT WILL OUTPUT AS THE NAME OF THAT OF YOU HAVE GIVEN WHILE CREATING THE FILE
             BUT WHERE WE HAVE IF IMPORTED THERE IF WE print(__name__) USE THIS IT WILL PRINT __MAIN__ ONLY BECAUSE WE ARE RUNNING THE FILE DIRECTLY 
             ALL TOGETHER--> THE THING IS IF A FILE IS RUN DIRECTLY IT RETURN THE __MAIN__ AS OUTPUT BUT IF WE ARE IMPORTING AS AN IN SOME ANOTHER THEN IT 
             WILL RETURN THE NAME OF THE ORIGINAL FILE WHERE THE FUNCTIION ARE ACTUALLY PRESENT'''